### ISSUE TITLE
Redirect https://turing.ml/ to https://turinglang.org/

### ISSUE THREAD

**Issue by LilithHafner** [TuringLang/turinglang.github.io#59]
There are still a few links to https://turing.ml/ floating around (e.g. the top result of a duck duck go search, links from julialang.org)

![Pasted image 2](https://github.com/TuringLang/turinglang.github.io/assets/60898866/42310391-8cd2-4f89-921d-c6254f9dd6c4)

It would be great to redirect those instead of 404ing.

**Comment by qacwnfq** [comment]
Why was it moved? Also there is a link to a gambling site on turing.ml

See the free slots link:

![image](https://github.com/TuringLang/turinglang.github.io/assets/8685531/c2e68c62-5a0a-47f2-a762-940e1f7d7e38)

**Comment by LilithHafner** [comment]
It seems that someone has squatted that URL and put up a modified version of the old site.

**Comment by penelopeysm** [comment]
Closing in favour of https://github.com/TuringLang/Turing.jl/issues/2041
