### ISSUE TITLE
Link to tutorials broke

### ISSUE THREAD

**Issue by laygr** [TuringLang/turinglang.github.io#64]
I'm getting the following:

```
Page Not Found
The page you requested cannot be found (perhaps it was moved or renamed).

You may want to visit [Get-Started Guide](https://turinglang.org/docs/using-turing/getting-started/) or [Tutorials](https://turinglang.org/docs/tutorials/introduction/).
```

When clicking a link to the tutorials.

**Comment by shravanngoswamii** [comment]
sorry for the inconvenience, we are merging the website into Quarto so those links will stay broken for a few days! Still, you can get the tutorials or docs in the tutorials directory of this repo https://github.com/TuringLang/TuringTutorials/
