### ISSUE TITLE
Dark Mode for website

### ISSUE THREAD

**Issue by shravanngoswamii** [TuringLang/turinglang.github.io#91]
Implementing Dark/Light mode in Quarto is straightforward, but I'm waiting because there isn't a 'cosmo' equivalent theme for Dark mode. It would require writing some custom CSS for 'solar' theme, which is similar to 'cosmo' but have some color inconsistencies that need refining. 

@jitendravjh want to work on this - https://github.com/TuringLang/turinglang.github.io/issues/80#issuecomment-2268963967

**Comment by jitendravjh** [comment]
Working on it!!
