### ISSUE TITLE
Convert DovNav workflow into reusable Github Action

### ISSUE THREAD

**Issue by yebai** [TuringLang/turinglang.github.io#95]

**Comment by penelopeysm** [comment]
Just thinking out loud, but I do wonder if some of our Docs workflows can be abstracted away too into a shared action.

Happy to look into it if you want!

**Comment by shravanngoswamii** [comment]
> Just thinking out loud, but I do wonder if some of our Docs workflows (not just the navbar) can be abstracted away too into a shared action.

Like which one...?

**Comment by shravanngoswamii** [comment]
@penelopeysm, Can you please review this `https://github.com/shravanngoswamii/DocsNav` and suggest any changes! I just replicated our `DocsNav` workflow into composite action!

**Comment by penelopeysm** [comment]
> which ones

The basic Documenter setup (with some variation) is in most of the TuringLang repos:

https://github.com/TuringLang/Turing.jl/blob/pysm/docs/.github/workflows/Docs.yml (this is on a PR, not main branch)

https://github.com/TuringLang/DynamicPPL.jl/blob/master/.github/workflows/Docs.yml

https://github.com/TuringLang/AbstractMCMC.jl/blob/master/.github/workflows/Docs.yml

Abstracting these out would mean that (for example) we can issue an error or warning if a ssh key is not provided (while this is not mandatory, if we want things to work the way they should it pretty much is 😄

**Comment by shravanngoswamii** [comment]
> Abstracting these out would mean that (for example) we can issue an error or warning if a ssh key is not provided (while this is not mandatory, if we want things to work the way they should it pretty much is 😄

This looks reasonable! It definitely makes sense to have those checks in place to ensure everything runs smoothly!

**Comment by penelopeysm** [comment]
https://github.com/TuringLang/actions
