### ISSUE TITLE
`SliceSampling` does not appear in navbar?

### ISSUE THREAD

**Issue by Red-Portal** [TuringLang/turinglang.github.io#96]
Hi, 

Seems like `SliceSampling` is not under `Libraries` in the navigation bar. How can it be added?

**Comment by shravanngoswamii** [comment]
You can add it here in whatever sequence you like: https://github.com/TuringLang/turinglang.github.io/blob/5d0c9e74a53ae43f00ad6860f72527cee803daca/assets/scripts/TuringNavbar.html#L271C1-L289C25, Navigation bar workflow will run on Sunday midnight automatically so it will appear everywhere after that or else you can manually trigger `DocsNav` workflow!

**Comment by shravanngoswamii** [comment]
It's added here: https://turinglang.org/SliceSampling.jl/, It will be live everywhere after midnight!

**Comment by Red-Portal** [comment]
Thanks!
